name: Java CI QA

on:
  pull_request:
    branches: [ "qa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
