name: Java CI QA

on:
  pull_request:
    branches: [ "qa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 20
      uses: actions/setup-java@v4
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: samuelxavier10/nomedaimagem 
        tags: ${{ github.run_number}}
        registry: docker.io
        dockerfile: dockerfile
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
